# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-26 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.FileField(blank=True, max_length=255, upload_to=b'C:\\Users\\Yuemia\\Desktop\\learn_Django\\myDjango/static/upload/upimg')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6',
                'verbose_name_plural': '\u6587\u4ef6',
            },
        ),
    ]
